Tools¶
You will utilize functions from scikit-learn as well as matplotlib and NumPy.

Importing essential libraries

In [13]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler

providing the training data

In [23]:
x_train = np.array([
 [1.24e+03, 3.00e+00, 1.00e+00, 6.40e+01,],
 [1.95e+03, 3.00e+00, 2.00e+00, 1.70e+01,],
 [1.72e+03, 3.00e+00, 2.00e+00, 4.20e+01,],
 [1.96e+03, 3.00e+00, 2.00e+00, 1.50e+01,],
 [1.31e+03, 2.00e+00, 1.00e+00, 1.40e+01,],
 [8.64e+02, 2.00e+00, 1.00e+00, 6.60e+01,],
 [1.84e+03, 3.00e+00, 1.00e+00, 1.70e+01,],
 [1.03e+03, 3.00e+00, 1.00e+00, 4.30e+01,],
 [3.19e+03, 4.00e+00, 2.00e+00, 8.70e+01,],
 [7.88e+02, 2.00e+00, 1.00e+00, 8.00e+01,],
 [1.20e+03, 2.00e+00, 2.00e+00, 1.70e+01,],
 [1.56e+03, 2.00e+00, 1.00e+00, 1.80e+01,],
 [1.43e+03, 3.00e+00, 1.00e+00, 2.00e+01,],
 [1.22e+03, 2.00e+00, 1.00e+00, 1.50e+01,],
 [1.09e+03, 2.00e+00, 1.00e+00, 6.40e+01,],
 [8.48e+02, 1.00e+00, 1.00e+00, 1.70e+01,],
 [1.68e+03, 3.00e+00, 2.00e+00, 2.30e+01,],
 [1.77e+03, 3.00e+00, 2.00e+00, 1.80e+01,],
 [1.04e+03, 3.00e+00, 1.00e+00, 4.40e+01,],
 [1.65e+03, 2.00e+00, 1.00e+00, 2.10e+01,],
 [1.09e+03, 2.00e+00, 1.00e+00, 3.50e+01,],
 [1.32e+03, 3.00e+00, 1.00e+00, 1.40e+01,],
 [1.59e+03, 0.00e+00, 1.00e+00, 2.00e+01,],
 [9.72e+02, 2.00e+00, 1.00e+00, 7.30e+01,],
 [1.10e+03, 3.00e+00, 1.00e+00, 3.70e+01,],
 [1.00e+03, 2.00e+00, 1.00e+00, 5.10e+01,],
 [9.04e+02, 3.00e+00, 1.00e+00, 5.50e+01,],
 [1.69e+03, 3.00e+00, 1.00e+00, 1.30e+01,],
 [1.07e+03, 2.00e+00, 1.00e+00, 1.00e+02,],
 [1.42e+03, 3.00e+00, 2.00e+00, 1.90e+01,],
 [1.21e+03, 3.00e+00, 1.00e+00, 2.00e+01,],
 [1.05e+03, 2.00e+00, 1.00e+00, 6.50e+01,],
])
y_train = np.array([300, 509.8, 394, 540, 415, 230, 560, 294, 718.2, 200,
 302, 468, 374.2, 388, 282, 311.8, 401, 449.8, 301, 502,
 340, 400.28, 572, 264, 304, 298, 219.8, 490.7, 216.96, 368.2,
 280, 526.87])


Normalizing the data

In [24]:
scaler = StandardScaler()
x_norm = scaler.fit_transform(x_train)
print (x_norm)

[[-0.2751289   0.70894901 -0.57735027  1.05803297]
 [ 1.24356124  0.70894901  1.73205081 -0.82737175]
 [ 0.75159119  0.70894901  1.73205081  0.1755031 ]
 [ 1.26495124  0.70894901  1.73205081 -0.90760174]
 [-0.12539889 -0.62554324 -0.57735027 -0.94771673]
 [-1.07939297 -0.62554324 -0.57735027  1.13826295]
 [ 1.00827122  0.70894901 -0.57735027 -0.82737175]
 [-0.72431894  0.70894901 -0.57735027  0.21561809]
 [ 3.89592148  2.04344126  1.73205081  1.98067783]
 [-1.24195699 -0.62554324 -0.57735027  1.69987287]
 [-0.36068891 -0.62554324  1.73205081 -0.82737175]
 [ 0.40935116 -0.62554324 -0.57735027 -0.78725676]
 [ 0.13128114  0.70894901 -0.57735027 -0.70702677]
 [-0.3179089  -0.62554324 -0.57735027 -0.90760174]
 [-0.59597893 -0.62554324 -0.57735027  1.05803297]
 [-1.11361698 -1.96003549 -0.57735027 -0.82737175]
 [ 0.66603119  0.70894901  1.73205081 -0.58668179]
 [ 0.8585412   0.70894901  1.73205081 -0.78725676]
 [-0.70292894  0.70894901 -0.57735027  0.25573309]
 [ 0.60186118 -0.62554324 -0.57

In [39]:
sgdr = SGDRegressor(max_iter=1000)
print(x_train.shape)
print(y_train.shape)
sgdr.fit(x_norm,y_train)
print(sgdr)
print(f"number of iterations completed: {sgdr.n_iter_}, number of weight updates: {sgdr.t_}")

(32, 4)
(32,)
SGDRegressor()
number of iterations completed: 299, number of weight updates: 9569.0


To view the parameter we have 

In [41]:
b_norm = sgdr.intercept_
w_norm = sgdr.coef_
print(f"model parameters:                   w: {w_norm}, b:{b_norm}")

model parameters:                   w: [128.52142484 -29.79837777 -24.81623831 -23.29065227], b:[381.9176841]


Make predictions¶
Predict the targets of the training data. Use both the predict routine and compute using  𝑤
  and  𝑏
 .

In [43]:
# make a prediction using sgdr.predict()
y_pred_sgd = sgdr.predict(x_norm)
# make a prediction using w,b. 
y_pred = np.dot(x_norm, w_norm) + b_norm  
print(f"prediction using np.dot() and sgdr.predict match: {(y_pred == y_pred_sgd).all()}")

print(f"Prediction on training set:\n{y_pred[:4]}" )
print(f"Target values \n{y_train[:4]}")

prediction using np.dot() and sgdr.predict match: True
Prediction on training set:
[315.11757941 496.90345831 410.3171577  501.52114059]
Target values 
[300.  509.8 394.  540. ]
